### ISSUE TITLE
[Functional] [T24][MU] start date is displayed as 1/1/2016 and end date as 31/12/2015

### ISSUE THREAD

**Issue by TeamResearch** [MohanRao13/BugBash-Cerner#103]
Steps to reproduce:

step 1: Open stroke summary report
step 2 : Provide future date to retrieve data.
report is opened  with all values as 0. 
start date is displayed as 1/1/2016 and end date as 31/12/2015

**Comment by sharathbhat** [comment]
known Issue; client never use this workflow
