### ISSUE TITLE
[Functional][T19][Mpages]::[The page was unable to load error]

### ISSUE THREAD

**Issue by Jairaj19** [MohanRao13/BugBash-Cerner#234]
![error mpage](https://cloud.githubusercontent.com/assets/13677872/9170448/8fc4f74e-3f80-11e5-8450-222e4a8216c2.jpg)
Mpages:

Steps to reproduce:

Load the patient and click on the Histories tab from the panel and try to press tab multiple times and note that unable to load the error is displayed.

**Comment by MohanRao13** [comment]
Invalid !

Manas
