### ISSUE TITLE
[Fuctional][T18[MU]:Page navigation does not display appropriate page number in meaningful use 

### ISSUE THREAD

**Issue by NatarajHiremath** [MohanRao13/BugBash-Cerner#279]
report: emeasures ed 2015

report shows 21 pages
enter 1 in the page navigator --> it displays 1/1+
when 21 is entered it shows 21/21
but now enter 1 and it shows 1/21

Inappropriate display of page numbers in meaningful use

**Comment by sharathbhat** [comment]
Not able to reproduce
