### ISSUE TITLE
[Functional][T14][MU][Unable to cancel Run Query Process]

### ISSUE THREAD

**Issue by nimeshika** [MohanRao13/BugBash-Cerner#389]
Application Name :Meaningful Use
Steps:
1)Navigate to PC Detail Report.
2)Click on "Refresh All" ,a window appears.
3)Click on "Run Query",a loading bar appears.
4)Click on "Cancel" button while it is in middle of loading but it does not cancel the process.

**Comment by sharathbhat** [comment]
SAP issue
