### ISSUE TITLE
[Functional][T4][MPages]: modify, delete responsible provider failure message 

### ISSUE THREAD

**Issue by ashwinim5** [MohanRao13/BugBash-Cerner#40]
Issue:
1)Load patient 
2)IN HISTORY TAB expand chronic problem and right click on value, modify, delete responsible provider

Issue: Error pop up with Failure Status "Action was not successful"

**Comment by ashwinim5** [comment]
Issue :

**Comment by MohanRao13** [comment]
Invalid !

Manas
