### ISSUE TITLE
[Cosmetic][T19] [MU] in the date format if \ is given data is still getting retrieved

### ISSUE THREAD

**Issue by Jairaj19** [MohanRao13/BugBash-Cerner#419]
in the date format if \ is given data is still getting retrieved. If slash is removed as well there is no indication

**Comment by Jairaj19** [comment]
![date format issue](https://cloud.githubusercontent.com/assets/13677872/9171461/525ede70-3f89-11e5-972e-1e6290b93146.jpg)

**Comment by sharathbhat** [comment]
it will display old data, it will not get refresh when we give the date in different format
