### ISSUE TITLE
[UI][T14] [MU] [Footer Behavior Inconsistent]

### ISSUE THREAD

**Issue by nimeshika** [MohanRao13/BugBash-Cerner#437]
Application Name :Meaningful Use
Steps:
1)Under "PC Report Tab" the footer "Cerner Corporation: eMeasures Reporting (US)" is displayed sometimes but sometimes it is not displayed.Behavior is inconsistent.
![sai](https://cloud.githubusercontent.com/assets/13725116/9171436/1ccfd02a-3f89-11e5-8dbf-0341a8fc8ee6.png)

**Comment by sharathbhat** [comment]
displaying correctly.
